// Inputsystem library for Uranium (engine)
// By DREADCRAFT
//

#ifndef INPUTSYSTEM_H
#define INPUTSYSTEM_H

#include "stdio.h"
#include "stdbool.h"
#include "stdlib.h"
#include "math.h"
#include "string.h"

#include "SDL2/SDL.h"

#define INPUT_KEY_A SDL_SCANCODE_A
#define INPUT_KEY_B SDL_SCANCODE_B
#define INPUT_KEY_C SDL_SCANCODE_C
#define INPUT_KEY_D SDL_SCANCODE_D
#define INPUT_KEY_E SDL_SCANCODE_E
#define INPUT_KEY_F SDL_SCANCODE_F
#define INPUT_KEY_G SDL_SCANCODE_G
#define INPUT_KEY_H SDL_SCANCODE_H
#define INPUT_KEY_I SDL_SCANCODE_I
#define INPUT_KEY_J SDL_SCANCODE_J
#define INPUT_KEY_K SDL_SCANCODE_K
#define INPUT_KEY_L SDL_SCANCODE_L
#define INPUT_KEY_M SDL_SCANCODE_M
#define INPUT_KEY_N SDL_SCANCODE_N
#define INPUT_KEY_O SDL_SCANCODE_O
#define INPUT_KEY_P SDL_SCANCODE_P
#define INPUT_KEY_Q SDL_SCANCODE_Q
#define INPUT_KEY_R SDL_SCANCODE_R
#define INPUT_KEY_S SDL_SCANCODE_S
#define INPUT_KEY_T SDL_SCANCODE_T
#define INPUT_KEY_U SDL_SCANCODE_U
#define INPUT_KEY_V SDL_SCANCODE_V
#define INPUT_KEY_W SDL_SCANCODE_W
#define INPUT_KEY_X SDL_SCANCODE_X
#define INPUT_KEY_Y SDL_SCANCODE_Y
#define INPUT_KEY_Z SDL_SCANCODE_Z

#define INPUT_KEY_0 SDL_SCANCODE_0
#define INPUT_KEY_1 SDL_SCANCODE_1
#define INPUT_KEY_2 SDL_SCANCODE_2
#define INPUT_KEY_3 SDL_SCANCODE_3
#define INPUT_KEY_4 SDL_SCANCODE_4
#define INPUT_KEY_5 SDL_SCANCODE_5
#define INPUT_KEY_6 SDL_SCANCODE_6
#define INPUT_KEY_7 SDL_SCANCODE_7
#define INPUT_KEY_8 SDL_SCANCODE_8
#define INPUT_KEY_9 SDL_SCANCODE_9

#define INPUT_KEY_ESCAPE SDL_SCANCODE_ESCAPE
#define INPUT_KEY_ENTER SDL_SCANCODE_RETURN
#define INPUT_KEY_SPACE SDL_SCANCODE_SPACE
#define INPUT_KEY_LSHIFT SDL_SCANCODE_LSHIFT
#define INPUT_KEY_RSHIFT SDL_SCANCODE_RSHIFT
#define INPUT_KEY_LCTRL SDL_SCANCODE_LCTRL
#define INPUT_KEY_RCTRL SDL_SCANCODE_RCTRL
#define INPUT_KEY_LALT SDL_SCANCODE_LALT
#define INPUT_KEY_RALT SDL_SCANCODE_RALT
#define INPUT_KEY_TAB SDL_SCANCODE_TAB
#define INPUT_KEY_BACKSPACE SDL_SCANCODE_BACKSPACE

#define INPUT_KEY_UP SDL_SCANCODE_UP
#define INPUT_KEY_DOWN SDL_SCANCODE_DOWN
#define INPUT_KEY_LEFT SDL_SCANCODE_LEFT
#define INPUT_KEY_RIGHT SDL_SCANCODE_RIGHT

#define INPUT_KEY_F1 SDL_SCANCODE_F1
#define INPUT_KEY_F2 SDL_SCANCODE_F2
#define INPUT_KEY_F3 SDL_SCANCODE_F3
#define INPUT_KEY_F4 SDL_SCANCODE_F4
#define INPUT_KEY_F5 SDL_SCANCODE_F5
#define INPUT_KEY_F6 SDL_SCANCODE_F6
#define INPUT_KEY_F7 SDL_SCANCODE_F7
#define INPUT_KEY_F8 SDL_SCANCODE_F8
#define INPUT_KEY_F9 SDL_SCANCODE_F9
#define INPUT_KEY_F10 SDL_SCANCODE_F10
#define INPUT_KEY_F11 SDL_SCANCODE_F11
#define INPUT_KEY_F12 SDL_SCANCODE_F12

// Input state checking macros
#define KEY_DOWN(key) (Input_GetKeyState(key) == 1)
#define KEY_PRESSED(key) (Input_GetKeyPressed(key))
#define KEY_RELEASED(key) (Input_GetKeyReleased(key))
#define KEY_UP(key) (Input_GetKeyState(key) == 0)

void Input_Init(void);
void Input_Update(void);
void Input_Shutdown(void);

// Key state functions
int Input_GetKeyState(int key);
int Input_GetKeyPressed(int key);
int Input_GetKeyReleased(int key);

#endif // INPUTSYSTEM_H
